# version: '3.8'


# services:

#   postgres-db:
#     image: postgres:15.3
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_DB: mydb
#       POSTGRES_PASSWORD: postgres
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
#     ports:
#       - 5432:5432

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb?schema=public
    ports:
      - "3000:3000"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm start"

volumes:
  postgres_data:


